name: LisaMarie
favicon: null
layout_spectrum: 0.9578266264870763
typography_spectrum: 0.4590372999664396
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#241f20'
    - '#ff0085'
    - '#6a6667'
    - '#ff7fc7'
  brandStrength: 0.12502593942917883
  lightness: 0.5318195074796677
  saturation: 0.8825887341517955
  rhythmicContrast: 0.5987274076323956
purpose: []
